name: json_model
description: Gernerating Dart model class from Json file.
version: 0.0.2
author: wendux <824783146@qq.com>
homepage: https://github.com/flutterchina/json_model

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^2.1.1
  build: ^2.0.0
  glob: ^2.0.1
  logging: ^1.0.1
  io: ^1.0.0
  build_resolvers: ^2.0.3
  build_runner_core: ^7.0.0
  build_runner: ^2.0.4
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  path: ^1.6.2
dev_dependencies:
  test: ^1.17.5
